language: clojure
script: lein with-profile production compile :all
deploy:
  - provider: releases
    api_key:
      secure: kvygJ/E+YVe0sSuDZXaNYtn9DXxx8RovAvCDnsdMjEkWYwTfg8yUaMdlqvzzYojym/FKRr05RzSjClDbWJ8JnU4su2iMjOMuHzrhH8UALZQIM2yaxporVugh32OYSFZDYEA2oUwg0TRD7GPfb7aJYbkmu2AWb5ZubCwXQKSWauOFVnXY6xmCZl7Z+0xAZJBHFch7LyGXk2tc3sYd4qwSla46ysVj0AB5A5ymQbmrlg+QIk5jOBDB6/3Q947Lzq9tupjuMH7dB1bmYJ3vAXBbUfVpTtlAFYjnsUF0R5kJca2G2VGputKgIvU68OuTu+UgRTrMJBKY6W1cuP9NuWR1/dvNE6H8rW0mL5xBUwYtTkNlh6YkAAUkkIh0gEB2X4MpA73dVdNv3gwQoSFysGT0tO4kHlNwgGPYY1iuHJPkjMImxP4p3L3MpQa7+KyxOafKwIX9BkZW+jY6vcv+TGt0Wi3Lw4RSMq8twFes+GgI+OiBasg1myOqpWsaPkgSucm+2KE66EnA09tq5fO5fw0PxlDej6HHFvALrqmLrjQemfvUvw606pwC9UjELs3Ia8v7kKE2Vovd/7kA+KCe3Vds8s+T6f+dPhQLQOOSNIuR9MuXQo14mbjc4mJXv6GJC80OoJhCqDXodAqrnFM8WhXxDmUfAMFU/hV2QbF4tII5SSk=
    file: resources/public/js/hap-browser.js
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: AKIAJLIJBGPEY43IMJ6Q
    secret_access_key:
      secure: IrdRJf8DxDU4FZvhaBFKL0OHT+uF2YpLvmIBhqR2qKATE5qakvf6aplJJlkyOxcdojlMHru+lJ4+5DpXtlOP/ACY2kL1dhA1AFXev3LKEba4lOIT1UlROr19YxA+BPem07ygnXZPJ9z1MIJQR67Gg6kz2JIQe9PkUfpwPqS0tnNKiEXbf38pjPDGogTyLITy7jxkF2rB9DvKORhgmSM1qj91g5MvW/l0IzfYDYzPbWkhiGyRr6NRL0+zXxKHi3o4i5QiKazk6O1UtFnT6mn3Mpp+WEE4K1G+PTq2Z9AQqrXMO0Qcbo3totC60RE4KlcfbPWxCtqPG6gxvlnZAJPoeWhFwcaS+YdaDkHsAYgOEjWiRZbAMK+LHgCWaU4R/VWuNb+iJ4PgHlw4GR+9iirGiObOHLIzhjQaTq1eKQJxwhKqswWn8+D23S2Gxfck8fG+uDp67SsOJZkZseqqFDRclBYWD4sZlD/MR3ghiF1o6/oLtN2eXyZHZk60A+mf2Tx7iU+55/wXGe/t4WV9c+G+rKMSIxZC62G11KAZcp57koWkhQBpaBPwBy93DDXXT3OL6Q/ImqytRcv5XhjFR1MOyOLvOacXNFJlZWnvoMEI+r8KVyj/CasfO9FixCdHgL8rLXUeBZfA7fmioW8BLXW3l20cDaQdD6DuE69Q+hh4z2M=
    bucket: hap-browser
    local-dir: resources/public/js
    skip_cleanup: true
    region: eu-central-1
    endpoint: s3.eu-central-1.amazonaws.com
after_deploy: 'curl -H "Content-Type: application/json" --data ''{"build": true}'' -X POST https://registry.hub.docker.com/u/akiel/hap-browser/trigger/5e9627af-ef1c-4dd5-bf59-af2cdcbb2272/'
